### ISSUE TITLE
en-US Typo: Commercial

### ISSUE THREAD

**Issue by baka-gourd** [RealTitanGod/SuperFastBuildingAndLeveling#1]
https://github.com/RealTitanGod/InfiniteDemand/blob/efec03727805e5dd5c05eadefb71bcf6d0c46859/InfiniteDemand/Settings.cs#L142

https://github.com/baka-gourd/I18NEverywhere.Localization/commit/e9118d7105847e29d87a28717603ab28939046fe#r144187247

an attentive translator caught this mistake

**Comment by RealTitanGod** [comment]
Thank you!
